// Generated by CoffeeScript 1.10.0
(function() {
  var assert, errors, test;

  require('colors');

  test = 0;

  errors = 0;

  assert = function(tests, statement, msg) {
    var m, n, pre;
    test++;
    n = test + "";
    m = tests.length + "";
    if (n.length === 1) {
      n = test + " ";
    }
    if (m.length === 1) {
      m = tests.length + " ";
    }
    pre = "test " + n + " of " + m;
    if (statement) {
      return console.log("+ PASSED\t".green, ("" + pre).yellow);
    } else {
      errors++;
      console.log("- FAILED\t".underline.red, "" + pre);
      return console.warn(msg);
    }
  };

  module.exports = assert;

}).call(this);
