// Generated by CoffeeScript 1.10.0
(function() {
  var animals, average, colors, end, i, now, results, start, total, v;

  now = require('performance-now');

  animals = require('../bin/index.js');

  colors = require('colors');

  console.log(colors.bgGreen("\nPerformance Testing\n"));

  console.log("Measurements in milliseconds (ms)");

  console.log(colors.bold("\tMeasuring 10 sets of 1000 great-animal uuid's:\n"));

  results = (function() {
    var j, k, results1;
    results1 = [];
    for (i = j = 1; j <= 10; i = ++j) {
      start = now();
      for (v = k = 1; k <= 1000; v = ++k) {
        animals();
      }
      end = now();
      console.log(colors.yellow("\tElapsed: ~" + ((end - start).toFixed(3)) + " ms"));
      results1.push(end - start);
    }
    return results1;
  })();

  total = results.reduce((function(accum, value) {
    return accum += value;
  }), 0);

  average = total / results.length;

  console.log(colors.bgGreen("\nResults:\n"));

  console.log("+\tTotal: " + (total.toFixed(6)) + " ms");

  console.log("+\tAverage (set of 1000): " + (average.toFixed(6)) + " ms");

  console.log("+\tAverage (single): " + ((average / 1000).toFixed(6)) + " ms");

}).call(this);
