// Generated by CoffeeScript 1.10.0
(function() {
  var animal, assert, tests;

  animal = require('../bin/index.js');

  assert = require('./assert.js');

  tests = [
    function() {
      return assert(tests, animal().length > 0, "Animal should generate a non-empty string");
    }, function() {
      var animals, v;
      animals = (function() {
        var i, results;
        results = [];
        for (v = i = 0; i < 10; v = ++i) {
          results.push(animal());
        }
        return results;
      })();
      return animals.sort().map(function(m, el) {
        assert(tests, m !== el, "Animal should generate unique strings");
        return el;
      });
    }, function() {
      var t;
      t = animal({
        tokenLength: 10
      }).split("-");
      return assert(tests, t[t.length - 1].length === 10, "options.tokenLength should adjust the token length");
    }, function() {
      return assert(tests, animal({
        delimiter: "_"
      }).indexOf("-" === -1, "options.delimiter should change the delimiter"));
    }
  ];

  console.time("Duration");

  tests.forEach(function(test, n) {
    return test.call();
  });

  console.timeEnd("Duration");

  console.log("Tests Complete.");

}).call(this);
